import type { Metadata } from "next";
import Header from "./header/header";
import Footer from "./footer/footer";
import "../../public/css/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="shortcut icon" href="/favicon.co" type="image/x-icon" />
      </head>
      <body>
        <div className="page-container">
          <Header />
          <main className="content">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
